# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e99f2dfd90f00b697f8c7efd585948f9db693f1a2173cf3eecd675be1201893c85267945f10b5b87acb1aeb50627551dcee46a6d625e571f762383e89e83e293

test:
  secret_key_base: 886766c55908e31330d3f2d050c3dfc6e194a2cc484371aad415510204d71b6093f6709eb88d93d9c29fe5bb6d2344a3d05a3effe2b8a3a577d17830b7aca430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
